---
- hosts: raspiHadoopCluster
  remote_user: pi
  become: yes
  tasks:
  - name: create users  
    user: 
      name: hadoop 
      comment: hadoop service account
  - name: verify headless openJDK 8 jre
    apt: 
      name: openjdk-8-jre-headless  
      state: present
      
  # We have to remove all the OpenJDK 11 stuff found on the Raspbian base OS    
  - name: verify absense JRE 11
    apt: 
      name: openjdk-11-jre 
      state: absent
  - name: verify absense jre 11 headless
    apt: 
      name: openjdk-11-jre-headless 
      state: absent  
  - name: verify absense jdk 11                  
    apt: 
      name: openjdk-11-jdk 
      state: absent
  - name: verify absense jdk 11 headless
    apt: 
      name: openjdk-11-jdk-headless 
      state: absent                  

 # Hadoop Dependencies
  - name: Verify Rsync
    apt:
      name: rsync
      state: present

  # Apt Cleanup
  - name: remove useless packages from the cache
    apt:
      autoclean: yes
  - name: remove dependencies that are no longer required
    apt:
      autoremove: yes
    
    
# MASTER 

- hosts: raspiHadoopNameNode
  remote_user: pi
  become: yes
  tasks:
  - name: Verify user local ssh folder
    file:
      path: /home/hadoop/.ssh
      state: directory
      mode: '0755'
      owner: hadoop
      group: hadoop
  - name: Create keys for hadoop user on master node
    openssh_keypair:
      path: /home/hadoop/.ssh/id_rsa
      owner: hadoop
      group: hadoop
    notify: 
        - Save Master Keys
    - name: Add data node host keys to master node known hosts
      blockinfile:
        block: "{{ lookup('file', 'keys/dataNode/host_key_{{ansible_hostname}}.pub') }}"
        dest: /home/
        
  handlers:
    - name: Save Master Keys
      fetch:
        src: /home/hadoop/.ssh/id_rsa.pub
        dest: keys/nameNode/id_rsa_nameNode_hadoopUser.pub
        flat: yes
      
# Data Nodes

- hosts: raspiHadoopDataNode
  remote_user: pi
  become: yes
  tasks:
  - name: Save Data Node Host Keys
    fetch: 
      src: /etc/ssh/ssh_host_rsa_key.pub
      dest: keys/dataNode/host_key_{{ansible_hostname}}.pub
      flat: yes
  - name: Add hadooop@masternode key to hadoop@dataNodeX authorized keys
    blockinfile:
      block: "{{ lookup('file', 'keys/nameNode/id_rsa_nameNode_hadoopUser.pub') }}"
      dest: /home/hadoop/.ssh/authorized_keys
      insertafter: EOF
      create: yes
      owner: hadoop
      group: hadoop
...
